language: node_js
node_js:
  - v8
  - v7
  - v6
os:
  - linux
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm install